---
- name: Create a Rackspace Cloud Server
  hosts: mc
  gather_facts: True

  tasks:
   - name: update all packages
     apt: update_cache=yes upgrade=yes
   - name: Add Debian non-free to be able to get the non-free fastcgi module
     apt_repository: repo='deb http://mirrorservice.org/sites/ftp.debian.org/debian/ {{ ansible_lsb.codename }} non-free' state=present
   - name: Install zee packagez
     apt: name={{item}} state=latest update_cache=yes cache_valid_time=50
     with_items:
             #minecraft stuffs
             - openjdk-7-jdk
               #python stuffs
             - python-virtualenv
             - python
             - python-setuptools
             - python-dev
             - gcc
             - python-pip
               #utils
             - zip
             - dos2unix
             - git
             - git-man
             - telnet
             - lynx
             - curl
             - sysstat
             - lsof
             - dnsutils
             - whois
             - screen
             - tcpdump
   - name: remove zee packagez
     apt: name={{item}} state=absent update_cache=yes cache_valid_time=50
     with_items:
             - pandoc
             - haskell-platform
   - name: add user
     user: name=nb state=present shell=/bin/bash groups=sudo generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
   - authorized_key: user=nb key="{{ lookup('file', '/home/nb/.ssh/id_rsa.pub') }}"
